package com.patientcase.audit;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    CASE_CREATED,
    CASE_UPDATED,
    ENCOUNTER_CREATED,
    ENCOUNTER_UPDATED,
    DIAGNOSIS_CREATED,
    TREATMENT_CREATED,
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    DOCUMENT_UPLOADED,
    AI_DRAFT_GENERATED,
    AI_DRAFT_APPLIED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    INTAKE_CREATED,
    INTAKE_SUBMITTED,
    INTAKE_ACCEPTED,
    INTAKE_REJECTED,
    RED_FLAG_IDENTIFIED
}
