package com.patientcase.audit;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    CASE_CREATED,
    CASE_UPDATED,
    ENCOUNTER_CREATED,
    ENCOUNTER_UPDATED,
    DIAGNOSIS_CREATED,
    TREATMENT_CREATED,
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    DOCUMENT_UPLOADED
}
